default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("PG_DB_NAME") %>
  username: <%= ENV.fetch("PG_DB_USERNAME") %>
  password: <%= ENV.fetch("PG_DB_PASSWORD") %>
  host: <%= ENV.fetch("PG_DB_HOST") %>
  port: <%= ENV.fetch("PG_DB_PORT", 5432) %>

cable:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV.fetch("PG_DB_NAME") %>
  username: <%= ENV.fetch("PG_DB_USERNAME") %>
  password: <%= ENV.fetch("PG_DB_PASSWORD") %>
  host: <%= ENV.fetch("PG_DB_HOST") %>
  port: <%= ENV.fetch("PG_DB_PORT", 5432) %>